trigger:
- main

variables:
  - group: abc  # Ensure this variable group contains 'cidr_block' and 'region'

stages:
- stage: Tf_Validation
  displayName: Terraform Init and Validate
  jobs:
  - job: terraformsetup
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'

    - script: |
        echo "Configuring Git with PAT"
        git config --global url."https://$(git_pat)@github.com/".insteadOf "https://github.com/"
      displayName: 'Configure Git for PAT'

    - task: TerraformTaskV4@4
      displayName: 'Terraform Init'
      inputs:
        provider: 'aws'
        command: 'init'
        backendServiceAWS: 'aws-to-tf'
        backendAWSBucketName: 'for-tf-use'
        backendAWSKey: 'modules/terraform.tfstate'
    - script: |
        echo "New variable value: $(cidr_block)"
      name: useVars

    - task: TerraformTaskV4@4
      inputs:
        provider: 'aws'
        command: 'plan'
        environmentServiceNameAWS: 'aws-to-tf'