trigger:
  branches:
    include:
      - main  # Direct push triggers for main branch
      - develop  # Direct push triggers for develop branch

pr:
  branches:
    include:
      - develop  # PR triggers only for changes to the develop branch

parameters:
  - name: targetEnv
    type: string
    default: 'dev'  # Default environment
    values:
      - 'dev'
      - 'qa'
      - 'stg'

stages:
  - stage: DeployDev
    displayName: 'Deploy to Development'
    jobs:
      - template: templates/terraform-deploy.yml
        parameters:
          targetEnv: 'dev'

  - stage: DeployQa
    displayName: 'Deploy to QA'
    jobs:
      - template: templates/terraform-deploy.yml
        parameters:
          targetEnv: 'qa'

  - stage: DeployStg
    displayName: 'Deploy to Staging'
    jobs:
      - template: templates/terraform-deploy.yml
        parameters:
          targetEnv: 'stg'
