trigger:
- main

variables:
  - group: abc  # Ensure this variable group contains 'cidr_block' and 'region'

stages:
- stage: Tf_Validation
  displayName: Terraform Init and Validate
  jobs:
  - job: terraformsetup
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'

    - task: TerraformTaskV4@4
      displayName: 'Terraform Init'
      inputs:
        provider: 'aws'
        command: 'init'
        backendServiceAWS: 'aws-to-tf'
        backendAWSBucketName: 'for-tf-use'
        backendAWSKey: 'modules/terraform.tfstate'

    - task: Bash@3
      inputs:
        targetType: 'inline'
        scriptPath: ''
        script: |
          # Print variables for debugging
          echo "cidr_block: $(cidr_block)"
          echo "region: $(region)"
          
          # Export environment variables
          export TF_VAR_cidr_block="($cidr_block)"
          export TF_VAR_region="($region)"
          
          # Print exported environment variables for debugging
          echo "TF_VAR_cidr_block: $TF_VAR_cidr_block"
          echo "TF_VAR_region: $TF_VAR_region"
    - task: TerraformTaskV4@4
      displayName: 'Terraform Plan'
      inputs:
        provider: 'aws'
        command: 'plan'
        environmentServiceNameAWS: 'aws-to-tf'
