trigger:
- main

variables:
  - group: abc  # Ensure this variable group contains the variables 'cidr_block' and 'region'

stages:
- stage: Tf_Validation
  displayName: Terraform Init and Validate
  jobs:
  - job: terraformsetup
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'  # Install the latest version of Terraform

    - script: |
        # Print the variable values for debugging
        echo "cidr_block: $(cidr_block)"
        echo "region: $(region)"
        
        # Export environment variables
        export TF_VAR_cidr_block="$(cidr_block)"
        export TF_VAR_region="$(region)"
        
        # Print the exported environment variables to confirm
        echo "TF_VAR_cidr_block: $TF_VAR_cidr_block"
        echo "TF_VAR_region: $TF_VAR_region"

    - task: TerraformTaskV4@4
      displayName: 'Terraform Init'
      inputs:
        provider: 'aws'
        command: 'init'
        backendServiceAWS: 'aws-to-tf'
        backendAWSBucketName: 'for-tf-use'
        backendAWSKey: 'modules/terraform.tfstate'

    - task: TerraformTaskV4@4
      displayName: 'Terraform Validate'
      inputs:
        provider: 'aws'
        command: 'validate'

    - task: TerraformTaskV4@4
      displayName: 'Terraform Plan'
      inputs:
        provider: 'aws'
        command: 'plan'
        environmentServiceNameAWS: 'aws-to-tf'