trigger:
- main

stages:

- stage: Tf_Validation
  displayName: Terraform Init and Validate
  jobs:
  - job: terraformsetup
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest' # Install the latest version of Terraform

    - script: |
        echo "Current directory:"
        pwd
        echo "Contents of the directory:"
        ls -la
      displayName: 'List files in working directory'

    - task: TerraformTaskV4@4
      displayName: 'Terraform Init'
      inputs:
        provider: 'aws'
        command: 'init'
        backendServiceAWS: 'aws-to-tf'
        backendAWSBucketName: 'for-tf-use'
        backendAWSKey: 'modules/terraform.tfstate'

    - task: TerraformTaskV4@4
      displayName: 'Terraform Validate'
      inputs:
        provider: 'aws'
        command: 'validate'

    - task: TerraformTaskV4@4
      displayName: 'Terraform Plan'
      inputs:
        provider: 'aws'
        command: 'plan'
        environmentServiceNameAWS: 'aws-to-tf'

    - task: TerraformTaskV4@4
      displayName: 'Terraform Apply'
      inputs:
        provider: 'aws'
        command: 'apply'
        environmentServiceNameAWS: 'aws-to-tf'
        commandOptions: '-auto-approve'
