trigger:
  branches:
    include:
      - develop

pr:
  branches:
    include:
      - develop

parameters:
  - name: environment
    type: string
    default: 'dev'
    values:
      - dev
      - qa
      - prod

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: Terraform
  displayName: 'Run Terraform'
  steps:
  - script: |
      echo "Selected environment: ${{ parameters.environment }}"
      cd env/${{ parameters.environment }}
      terraform init
      terraform apply -auto-approve
    displayName: 'Run Terraform'
