trigger:
  branches:
    include:
      - develop
  paths:
    include:
      - env/dev/**
      - env/qa/**
      - env/stg/**

jobs:
  - job: DeployDev
    displayName: 'Deploy to Dev'
    condition: eq(variables['Build.Reason'], 'PullRequest')
    variables:
      - group: dev-grp  # Reference to the variable group for Dev
    steps:
      - script: |
          git fetch origin +refs/pull/$(System.PullRequest.PullRequestId)/merge
          if git diff --name-only origin/develop | grep -q 'env/dev/'; then
            cd env/dev
            terraform init
            terraform apply -auto-approve -var="api_key=$(ApiKey)" -var="db_name=$(DbName)"
          else
            echo "No changes in env/dev/, skipping deployment."
          fi
        displayName: 'Deploy Terraform for Dev'

  - job: DeployQA
    displayName: 'Deploy to QA'
    condition: eq(variables['Build.Reason'], 'PullRequest')
    variables:
      - group: dev-grp  # Reference to the variable group for QA
    steps:
      - script: |
          git fetch origin +refs/pull/$(System.PullRequest.PullRequestId)/merge
          if git diff --name-only origin/develop | grep -q 'env/qa/'; then
            cd env/qa
            terraform init
            terraform apply -auto-approve -var="api_key=$(ApiKey)" -var="db_name=$(DbName)"
          else
            echo "No changes in env/qa/, skipping deployment."
          fi
        displayName: 'Deploy Terraform for QA'

  - job: DeployStg
    displayName: 'Deploy to Staging'
    condition: eq(variables['Build.Reason'], 'PullRequest')
    variables:
      - group: dev-grp  # Reference to the variable group for Staging
    steps:
      - script: |
          git fetch origin +refs/pull/$(System.PullRequest.PullRequestId)/merge
          if git diff --name-only origin/develop | grep -q 'env/stg/'; then
            cd env/stg
            terraform init
            terraform apply -auto-approve -var="api_key=$(ApiKey)" -var="db_name=$(DbName)"
          else
            echo "No changes in env/stg/, skipping deployment."
          fi
        displayName: 'Deploy Terraform for Staging'
