trigger:
  branches:
    include:
      - main
      - development

pr:
  branches:
    include:
      - development

parameters:
  - name: targetEnv
    type: string
    default: 'dev'
    values:
      - 'dev'
      - 'qa'
      - 'stg'

stages:
  - stage: DeployDev
    displayName: 'Deploy to Development'
    condition: and(startsWith(variables['Build.SourceBranch'], 'refs/pull/'), or(contains(variables['System.PullRequest.Title'], 'pr for dev'), contains(variables['System.PullRequest.Description'], 'pr for dev')))
    jobs:
      - template: templates/multi-env.yml
        parameters:
          targetEnv: 'dev'

  - stage: DeployQa
    displayName: 'Deploy to QA'
    condition: and(startsWith(variables['Build.SourceBranch'], 'refs/pull/'), or(contains(variables['System.PullRequest.Title'], 'pr for qa'), contains(variables['System.PullRequest.Description'], 'pr for qa')))
    jobs:
      - template: templates/multi-env.yml
        parameters:
          targetEnv: 'qa'

  - stage: DeployStg
    displayName: 'Deploy to Staging'
    condition: and(startsWith(variables['Build.SourceBranch'], 'refs/pull/'), or(contains(variables['System.PullRequest.Title'], 'pr for stg'), contains(variables['System.PullRequest.Description'], 'pr for stg')))
    jobs:
      - template: templates/multi-env.yml
        parameters:
          targetEnv: 'stg'
