trigger:
- main

variables:
  - group: abc  # Ensure this variable group contains 'cidr_block' and 'region'

stages:
- stage: Tf_Validation
  displayName: Terraform Init and Validate
  jobs:
  - job: terraformsetup
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'

    - task: TerraformTaskV4@4
      displayName: 'Terraform Init'
      inputs:
        provider: 'aws'
        command: 'init'
        commandOptions: 'git config --global url."https://${{ variables.github_token }}@github.com/".insteadOf "https://github.com/"'
        backendServiceAWS: 'aws-to-tf'
        backendAWSBucketName: 'for-tf-use'
        backendAWSKey: 'modules/terraform.tfstate'

    - task: TerraformTaskV4@4
      displayName: 'Terraform Plan'
      inputs:
        provider: 'aws'
        command: 'plan'
        environmentServiceNameAWS: 'aws-to-tf'
      env:
        TF_VAR_cidr_block: $(cidr_block)
        TF_VAR_region: $(region)
