trigger:
  branches:
    include:
      - main  # Direct push triggers for main branch

pr:
  branches:
    include:
      - develop  # PR triggers only for changes to the development branch

parameters:
  - name: targetEnv
    type: string
    default: 'dev'  # Default environment
    values:
      - 'dev'
      - 'qa'
      - 'stg'

stages:
  - stage: DeployDev
    displayName: 'Deploy to Development'
    condition: and(startsWith(variables['Build.SourceBranch'], 'refs/pull/'), not(empty(variables['System.PullRequest.Title'])), contains(toLower(variables['System.PullRequest.Title']), 'pr for dev'))
    jobs:
      - template: templates/multi-env.yml
        parameters:
          targetEnv: 'dev'

  - stage: DeployQa
    displayName: 'Deploy to QA'
    condition: and(startsWith(variables['Build.SourceBranch'], 'refs/pull/'), not(empty(variables['System.PullRequest.Title'])), contains(toLower(variables['System.PullRequest.Title']), 'pr for qa'))
    jobs:
      - template: templates/multi-env.yml
        parameters:
          targetEnv: 'qa'

  - stage: DeployStg
    displayName: 'Deploy to Staging'
    condition: and(startsWith(variables['Build.SourceBranch'], 'refs/pull/'), not(empty(variables['System.PullRequest.Title'])), contains(toLower(variables['System.PullRequest.Title']), 'pr for stg'))
    jobs:
      - template: templates/multi-env.yml
        parameters:
          targetEnv: 'stg'
