trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - develop
  paths:
    include:
      - env/dev/**
      - env/qa/**
      - env/stg/**

jobs:
  - job: DeployDev
    displayName: 'Deploy to Dev'
    condition: eq(variables['Build.Reason'], 'PullRequest')
    variables:
      - group: dev-grp  # Reference to the variable group for Dev
    steps:
      - script: |
          git diff --name-only HEAD^ HEAD > changed_files.txt
          if grep -q 'env/dev/' changed_files.txt; then
            cd env/dev
            terraform init
            terraform apply -auto-approve -var="api_key=$(ApiKey)" -var="db_name=$(DbName)"
          else
            echo "No changes in env/dev/, skipping deployment."
          fi
        displayName: 'Deploy Terraform for Dev'

  - job: DeployQA
    displayName: 'Deploy to QA'
    condition: eq(variables['Build.Reason'], 'PullRequest')
    variables:
      - group: dev-grp  # Reference to the variable group for QA
    steps:
      - script: |
          git diff --name-only HEAD^ HEAD > changed_files.txt
          if grep -q 'env/qa/' changed_files.txt; then
            cd env/qa
            terraform init
            terraform apply -auto-approve -var="api_key=$(ApiKey)" -var="db_name=$(DbName)"
          else
            echo "No changes in env/qa/, skipping deployment."
          fi
        displayName: 'Deploy Terraform for QA'

  - job: DeployStg
    displayName: 'Deploy to Staging'
    condition: eq(variables['Build.Reason'], 'PullRequest')
    variables:
      - group: dev-grp  # Reference to the variable group for Staging
    steps:
      - script: |
          git diff --name-only HEAD^ HEAD > changed_files.txt
          if grep -q 'env/stg/' changed_files.txt; then
            cd env/stg
            terraform init
            terraform apply -auto-approve -var="api_key=$(ApiKey)" -var="db_name=$(DbName)"
          else
            echo "No changes in env/stg/, skipping deployment."
          fi
        displayName: 'Deploy Terraform for Staging'
