jobs:
  - job: Deploy
    displayName: 'Deploy to Environments'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - checkout: self

      # Check for changes
      - script: |
          git fetch origin develop
          DEV_CHANGED=$(git diff --name-only origin/develop | grep -q 'env/dev/' && echo true || echo false)
          QA_CHANGED=$(git diff --name-only origin/develop | grep -q 'env/qa/' && echo true || echo false)
          STG_CHANGED=$(git diff --name-only origin/develop | grep -q 'env/stg/' && echo true || echo false)

          echo "DEV_CHANGED=$DEV_CHANGED"
          echo "QA_CHANGED=$QA_CHANGED"
          echo "STG_CHANGED=$STG_CHANGED"

          # Set output variables based on changes
          echo "##vso[task.setvariable variable=deployToDev]$DEV_CHANGED"
          echo "##vso[task.setvariable variable=deployToQA]$QA_CHANGED"
          echo "##vso[task.setvariable variable=deployToStg]$STG_CHANGED"
        displayName: 'Check for Changes'

      # Load environment-specific variable groups based on changes
      - ${{ if eq(variables['deployToDev'], 'true') }}:
        - group: dev-grp  # Variable group for Dev
      - ${{ if eq(variables['deployToQA'], 'true') }}:
        - group: qa-grp  # Variable group for QA
      - ${{ if eq(variables['deployToStg'], 'true') }}:
        - group: stg-grp  # Variable group for Staging

      # Deploy based on detected changes
      - script: |
          if [ "$(deployToDev)" = "true" ]; then
            echo "Deploying to Dev..."
            cd env/dev
            terraform init
            terraform plan
          fi

          if [ "$(deployToQA)" = "true" ]; then
            echo "Deploying to QA..."
            cd env/qa
            terraform init
            terraform apply -auto-approve -var="api_key=$(ApiKey)" -var="db_name=$(DbName)"
          fi

          if [ "$(deployToStg)" = "true" ]; then
            echo "Deploying to Staging..."
            cd env/stg
            terraform init
            terraform apply -auto-approve -var="api_key=$(ApiKey)" -var="db_name=$(DbName)"
          fi
        displayName: 'Deploy Terraform'
