trigger:
- main

variables:
  - group: abc  # Ensure this variable group contains 'cidr_block' and 'region'

stages:
- stage: Tf_Validation
  displayName: Terraform Init and Validate
  jobs:
  - job: terraformsetup
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'

    - task: Bash@3
      inputs:
        targetType: 'inline'
        scriptPath: ''
        script: |
          # Print variables for debugging
          echo "cidr_block: $(cidr_block)"
          echo "region: $(region)"
          
          # Export environment variables
          export TF_VAR_cidr_block=$(cidr_block)
          export TF_VAR_region=$(region)
          
          # Print exported environment variables for debugging
          echo "TF_VAR_cidr_block: $TF_VAR_cidr_block"
          echo "TF_VAR_region: $TF_VAR_region"

          # Run Terraform commands
          terraform init
          terraform validate
          terraform plan -detailed-exitcode
      displayName: 'Run Terraform Commands with Exported Variables'