stages:
  - stage: DeployDev
    displayName: 'Deploy to Development'
    condition: and(startsWith(variables['Build.SourceBranch'], 'refs/pull/'), contains(variables['Build.SourceVersionMessage'], 'pr for dev'))
    jobs:
      - template: templates/multi-env.yml
        parameters:
          targetEnv: 'dev'

  - stage: DeployQa
    displayName: 'Deploy to QA'
    condition: and(startsWith(variables['Build.SourceBranch'], 'refs/pull/'), contains(variables['Build.SourceVersionMessage'], 'pr for qa'))
    jobs:
      - template: templates/multi-env.yml
        parameters:
          targetEnv: 'qa'

  - stage: DeployStg
    displayName: 'Deploy to Staging'
    condition: and(startsWith(variables['Build.SourceBranch'], 'refs/pull/'), contains(variables['Build.SourceVersionMessage'], 'pr for stg'))
    jobs:
      - template: templates/multi-env.yml
        parameters:
          targetEnv: 'stg'
