trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - develop
  paths:
    include:
      - env/dev/**
      - env/qa/**
      - env/stg/**

jobs:
  - job: CheckChanges
    displayName: 'Check for Changes'
    steps:
      - checkout: self
      - script: |
          git fetch origin develop  # Fetch the develop branch
          echo "##vso[task.setvariable variable=DevChanged;isOutput=true]$(git diff --name-only origin/develop | grep -q 'env/dev/' && echo true || echo false)"
          echo "##vso[task.setvariable variable=QAChanged;isOutput=true]$(git diff --name-only origin/develop | grep -q 'env/qa/' && echo true || echo false)"
          echo "##vso[task.setvariable variable=StgChanged;isOutput=true]$(git diff --name-only origin/develop | grep -q 'env/stg/' && echo true || echo false)"
        displayName: 'Check for Directory Changes'

  - job: DeployDev
    displayName: 'Deploy to Dev'
    condition: eq(dependencies.CheckChanges.outputs['DevChanged'], 'true')
    variables:
      - group: dev-grp  # Reference to the variable group for Dev
    steps:
      - script: |
          cd env/dev
          terraform init
          terraform apply -auto-approve -var="api_key=$(ApiKey)" -var="db_name=$(DbName)"
        displayName: 'Deploy Terraform for Dev'

  - job: DeployQA
    displayName: 'Deploy to QA'
    condition: eq(dependencies.CheckChanges.outputs['QAChanged'], 'true')
    variables:
      - group: dev-grp  # Reference to the variable group for QA
    steps:
      - script: |
          cd env/qa
          terraform init
          terraform apply -auto-approve -var="api_key=$(ApiKey)" -var="db_name=$(DbName)"
        displayName: 'Deploy Terraform for QA'

  - job: DeployStg
    displayName: 'Deploy to Staging'
    condition: eq(dependencies.CheckChanges.outputs['StgChanged'], 'true')
    variables:
      - group: dev-grp  # Reference to the variable group for Staging
    steps:
      - script: |
          cd env/stg
          terraform init
          terraform apply -auto-approve -var="api_key=$(ApiKey)" -var="db_name=$(DbName)"
        displayName: 'Deploy Terraform for Staging'
