trigger:
  branches:
    include:
      - develop

pr:
  branches:
    include:
      - develop

parameters:
  - name: environment
    type: string
    default: 'dev'
    values:
      - dev
      - qa
      - prod

pool:
  vmImage: 'ubuntu-latest'

variables:
  variableGroup: 
    - dev: 'dev-group'
    - qa: 'QaVariableGroup'
    - prod: 'ProdVariableGroup'

jobs:
- job: Terraform
  displayName: 'Run Terraform'
  
  # Dynamically reference the variable group based on the selected environment
  variables:
    - group: ${{ variables['variableGroup'][parameters.environment] }}

  steps:
  - script: |
      echo "Selected environment: ${{ parameters.environment }}"
      cd env/${{ parameters.environment }}
      terraform init
      terraform apply -auto-approve
    displayName: 'Run Terraform'
