parameters:
  - name: environment
    type: string
    default: dev
    values:
      - dev
      - qa
      - prod
      
trigger:
  - develop

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: Terraform
  displayName: 'Run Terraform'
  
  # Dynamically select the variable group based on the environment
  variables:
    - group: dev-group

  steps:
  - script: |
      echo "Selected environment: ${{ parameters.environment }}"
      cd env/${{ parameters.environment }}
      terraform init
      terraform apply -auto-approve
    displayName: 'Run Terraform'
