trigger:
  branches:
    include:
      - develop

pr:
  branches:
    include:
      - develop

variables:
  targetEnvironment: ''  # Initialize variable

stages:
- stage: Prepare
  jobs:
  - job: SetEnvironment
    displayName: 'Determine Target Environment'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: |
        echo "Fetching the pull request title..."
        prTitle="$(System.PullRequest.Title)"
        echo "Pull Request Title: $prTitle"
        
        if [[ "$prTitle" == *"deploy to dev"* ]]; then
          echo "##vso[task.setvariable variable=targetEnvironment]dev"
        elif [[ "$prTitle" == *"deploy to qa"* ]]; then
          echo "##vso[task.setvariable variable=targetEnvironment]qa"
        elif [[ "$prTitle" == *"deploy to stage"* ]]; then
          echo "##vso[task.setvariable variable=targetEnvironment]stage"
        else
          echo "##vso[task.setvariable variable=targetEnvironment]none"
        fi
      displayName: 'Set Deployment Environment'

- stage: Deploy
  jobs:
  - job: DeployDev
    displayName: 'Deploy to Dev Environment'
    condition: eq(variables['targetEnvironment'], 'dev')
    pool:
      vmImage: 'ubuntu-latest'
    variables:
      - group: dev-grp  # Load Dev-specific variable group
    steps:
    - script: echo "Deploying to Dev environment"
    - task: UseTerraform@0
      inputs:
        command: 'init'
        workingDirectory: 'env/dev'
    - task: UseTerraform@0
      inputs:
        command: 'plan'
        workingDirectory: 'env/dev'
    - task: UseTerraform@0
      inputs:
        command: 'apply'
        workingDirectory: 'env/dev'
      env:
        AWS_ACCESS_KEY_ID: $(aws_access_key)
        AWS_SECRET_ACCESS_KEY: $(aws_secret_key)

  - job: DeployQa
    displayName: 'Deploy to QA Environment'
    condition: eq(variables['targetEnvironment'], 'qa')
    pool:
      vmImage: 'ubuntu-latest'
    variables:
      - group: qa-grp  # Load QA-specific variable group
    steps:
    - script: echo "Deploying to QA environment"
    - task: UseTerraform@0
      inputs:
        command: 'init'
        workingDirectory: 'env/qa'
    - task: UseTerraform@0
      inputs:
        command: 'plan'
        workingDirectory: 'env/qa'
        environmentServiceName: 'YourAWSServiceConnection'
        additionalArgs: '-out=tfplan'
    - task: UseTerraform@0
      inputs:
        command: 'apply'
        workingDirectory: 'env/qa'
        environmentServiceName: 'YourAWSServiceConnection'
        additionalArgs: 'tfplan'
      env:
        AWS_ACCESS_KEY_ID: $(aws_access_key)
        AWS_SECRET_ACCESS_KEY: $(aws_secret_key)

  - job: DeployStage
    displayName: 'Deploy to Stage Environment'
    condition: eq(variables['targetEnvironment'], 'stage')
    pool:
      vmImage: 'ubuntu-latest'
    variables:
      - group: stg-grp  # Load Stage-specific variable group
    steps:
    - script: echo "Deploying to Stage environment"
    - task: UseTerraform@0
      inputs:
        command: 'init'
        workingDirectory: 'env/stage'
    - task: UseTerraform@0
      inputs:
        command: 'plan'
        workingDirectory: 'env/stage'
        environmentServiceName: 'YourAWSServiceConnection'
        additionalArgs: '-out=tfplan'
    - task: UseTerraform@0
      inputs:
        command: 'apply'
        workingDirectory: 'env/stage'
        environmentServiceName: 'YourAWSServiceConnection'
        additionalArgs: 'tfplan'
      env:
        AWS_ACCESS_KEY_ID: $(aws_access_key)
        AWS_SECRET_ACCESS_KEY: $(aws_secret_key)
