trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self

- task: SonarCloudPrepare@2
  inputs:
    SonarCloud: 'tf-to-sc'
    organization: 'tf-to-sonarc'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: '017d27c8b3801e70d7b39311f4ffd190cd00845c'
    cliSources: '.'

- task: SonarCloudAnalyze@2

- task: SonarCloudPublish@2
  inputs:
    pollingTimeoutSec: '300'