trigger:
  branches:
    include:
      - develop

stages:
  - stage: DEV
    jobs:
      - template: templates/multi-env.yml
        parameters:
          stageName: 'dev-deploy'
          variableGroup: 'dev-group'
          environmentPath: 'env/dev'

  - stage: QA
    jobs:
      - template: templates/multi-env.yml
        parameters:
          stageName: 'qa-deploy'
          variableGroup: 'qa-group'
          environmentPath: 'env/qa'
