parameters:
  - name: targetEnv
    type: string

jobs:
  - job: Terraform
    displayName: 'Terraform Apply for $(targetEnv)'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - checkout: self

      # Set the environment directory based on the selected environment
      - script: |
          # Use the parameter correctly in the script
          ENV_DIR="env/${{ parameters.targetEnv }}"
          echo "Using environment directory: $ENV_DIR"

          # Check if the directory exists
          if [ ! -d "$ENV_DIR" ]; then
            echo "Error: Environment directory $ENV_DIR does not exist!"
            exit 1
          fi

          # Initialize Terraform
          cd $ENV_DIR
          terraform init
        displayName: 'Deploying with Terraform'
