parameters:
  - name: targetEnv
    type: string

jobs:
  - job: Terraform
    displayName: 'Terraform Apply for $(targetEnv)'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - checkout: self

      # Set the environment directory based on the selected environment
      - script: |
          ENV_DIR="env/$(targetEnv)"
          echo "Using environment directory: $ENV_DIR"

          # Initialize Terraform
          cd $ENV_DIR
          terraform init

          # Plan and apply
          terraform plan -var-file="variables.tf"
          terraform apply -auto-approve -var-file="variables.tf"
        displayName: 'Deploying with Terraform'
